### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by riccardocagnasso** [davidmhewitt/gst-plugin-ndi#7]
``[phas@mosconi gst-plugin-ndi]$ meson build --prefix=/usr
The Meson build system
Version: 0.57.0
Source dir: /home/phas/Downloads/gst-plugin-ndi
Build dir: /home/phas/Downloads/gst-plugin-ndi/build
Build type: native build
Project name: gst-plugin-ndi
Project version: undefined
C compiler for the host machine: cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35.1
Vala compiler for the host machine: valac (valac 0.50.4)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency glib-2.0 found: YES 2.66.7
Run-time dependency gobject-2.0 found: YES 2.66.7
Run-time dependency gstreamer-1.0 found: YES 1.18.3
Run-time dependency gstreamer-video-1.0 found: YES 1.18.3
Run-time dependency ndi found: YES 4.0
Build targets in project: 1

Found ninja-1.10.2 at /usr/bin/ninja
[phas@mosconi gst-plugin-ndi]$ cd build/
[phas@mosconi build]$ ninja
[1/4] Compiling Vala source ../src/gst-plugin-ndi.vala ../src/gst-ndi-sink.vala
FAILED: libgstndi.so.p/src/gst-plugin-ndi.c libgstndi.so.p/src/gst-ndi-sink.c gstndi.h gstndi.vapi 
valac -C --debug --debug --vapidir /home/phas/Downloads/gst-plugin-ndi/vapi --pkg ndi --pkg gstreamer-video-1.0 --pkg gstreamer-1.0 --pkg gobject-2.0 --pkg glib-2.0 --color=always --directory libgstndi.so.p --basedir ../ --library gstndi --header gstndi.h --vapi ../gstndi.vapi ../src/gst-plugin-ndi.vala ../src/gst-ndi-sink.vala
../src/gst-ndi-sink.vala:198.120-198.123: warning: Argument 3: Cannot pass null to non-null parameter type
            unowned Gst.Base.CollectData? collect_data = collect.add_pad (newpad, (uint)sizeof (Gst.Base.CollectData), null, true);
                                                                                                                       ^^^^
../src/gst-ndi-sink.vala:44.41-44.57: error: Argument 1: Cannot pass value to reference or output parameter
            Gst.ValueList.append_value (pixel_format_list, "UYVY");
                                        ^^^^^^^^^^^^^^^^^
../src/gst-ndi-sink.vala:45.41-45.57: error: Argument 1: Cannot pass value to reference or output parameter
            Gst.ValueList.append_value (pixel_format_list, "YV12");
                                        ^^^^^^^^^^^^^^^^^
../src/gst-ndi-sink.vala:46.41-46.57: error: Argument 1: Cannot pass value to reference or output parameter
            Gst.ValueList.append_value (pixel_format_list, "I420");
                                        ^^^^^^^^^^^^^^^^^
../src/gst-ndi-sink.vala:47.41-47.57: error: Argument 1: Cannot pass value to reference or output parameter
            Gst.ValueList.append_value (pixel_format_list, "NV12");
                                        ^^^^^^^^^^^^^^^^^
../src/gst-ndi-sink.vala:48.41-48.57: error: Argument 1: Cannot pass value to reference or output parameter
            Gst.ValueList.append_value (pixel_format_list, "BGRA");
                                        ^^^^^^^^^^^^^^^^^
../src/gst-ndi-sink.vala:49.41-49.57: error: Argument 1: Cannot pass value to reference or output parameter
            Gst.ValueList.append_value (pixel_format_list, "BGRx");
                                        ^^^^^^^^^^^^^^^^^
../src/gst-ndi-sink.vala:50.41-50.57: error: Argument 1: Cannot pass value to reference or output parameter
            Gst.ValueList.append_value (pixel_format_list, "RGBA");
                                        ^^^^^^^^^^^^^^^^^
../src/gst-ndi-sink.vala:51.41-51.57: error: Argument 1: Cannot pass value to reference or output parameter
            Gst.ValueList.append_value (pixel_format_list, "RGBx");
                                        ^^^^^^^^^^^^^^^^^
../src/gst-ndi-sink.vala:68.41-68.57: error: Argument 1: Cannot pass value to reference or output parameter
            Gst.ValueList.append_value (audio_format_list, "S16LE");
                                        ^^^^^^^^^^^^^^^^^
Compilation failed: 9 error(s), 1 warning(s)
ninja: build stopped: subcommand failed.
`
```

**Comment by davidmhewitt** [comment]
Looks like something changed in GStreamer or the compiler. Fixed in the latest commit
